language: Java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
- ./gradlew sonarqube
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: IraRe693JiCGgGolWK88bOuCVcLeLSb7h6B4/hYuG3MEGrvyKxnROuDkkF5XqzHB6B3evYAPK1gPkdF2x7Tzow/yAHc+ITygRX5DOr6aC/fQEgoOCEsdKPQGpgcz4MBAOayIPChpcdLqJGhdReRIc7XGKNMu2cy6Pwa5uI8OLnJVG0dNiQXP3da40L+XGi5UKRr7EULadkKpUDBVTmsZ+r4y5oBlTAIjcOpoXcxldmusCCUG6srPxRfD1OEZQJbFa2E/qSCiyLVgBSyImsgPLS/4Mp0FqoDfoVYNWorgd26OPQZE08SQ06x8Ws8Yd3CDjmTryu6tBB08k82Fe43LZGAaw15CRrRVV8Vv+pSicVx/Yu8oWykxKsInSyn2TWaE/wFO4ahXAXMMeIw7Yl/El/k1FUqj5Ywew3lMP1xuqBiVj+vmgezm8PN8nc0URSAF18wJsjI4gyxTDwn2x7LHP/WAQCFW77hHCBNCepO1ieqFdK2BACFlrcUSaKT6lNc5cQs7N49AqXV3+AAiLR93S750AMd/LmZmN1Oeq9ym7snN8+dRugKEceMdfIxPn7tUmd8TMve7beh/CLy0moR1q9OLvPApz0L9SVJUUUsjJL6ZU8HTeWyb8RsJtBWtH3K0v0ENg9zsqxxHFSnNIHHjNmynyJAtkGoShvNi/3X9w10=
  app: counterparty-service-staging
  skip_cleanup: true
  on:
    repo: spolnik/trading-office-counterparty-service
