language: Java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
- ./gradlew sonarqube
env:
  global:
  - secure: A+JodfRzulrwez5TVSm2k1SQPxsis68gM22JN4nqjm4RgekfHnfWe5OoLYhdFuhgyzkUE7AnmkhcZCtYpl4/hCtRs4pZ+Hum4vtSh99dLaMOW3CpUzaBpWPtCcuEN2DP3v8hMAkbqiaSEYxfKM94CH3Ct+YH8xuaMvcYsuBRaFz2KSJXnfor+111VGGjoDSRFqMd6cpq4m0U22vUtyCBVeu8+HPRn3ySyafL7hNCBNyZgkp1KZZPD6RgzHPbjVKA9lBO27CnSBsp3uWHv5Zfee80JFsjIECRhR5djYI/mq3xtWTsdnIOTEjiT8ahwpxJBrAscapt8iTmZolaYLoe97JLFcU4qQLQGsdg6SRcCbpiTFyu7oMqcApxdb+6er9I5B4XVN329xpTZLYsMFZAzeqhZswYxAJiRPIzS79y/WFBNMwlHPHYZauAMZTPiWK/+8sr3hyrtSyuzMms3puBAAvjfDKWI4QOIoVMUxp+O3gTHi29/UpegFwgEOMYXd2CspQROx76zq0G5xGeGK5FSRnvaE27VKPKlBdyE9DT8AZxy1sP9pigHCt4E/dV+4lM5awCCCqCVP5//yFrCFiTb0vINkZjYOhuaqckkAeKRa8/yZnGeXbZ4ENL+ZqVL/PnOdqd4jCS3uTSuW2s4N5AC7bXtCuHtiEWNj/siEzndE0=
addons:
  coverity_scan:
    project:
      name: spolnik/trading-office
      version: 1.0
      description: Trading Office
    notification_email: jacek.spolnik@gmail.com
    build_command_prepend: ./gradlew clean
    build_command: ./gradlew compileJava
    branch_pattern: coverity_scan
branches:
  only:
  - master
  - /^heroku-.*$/
  - coverity_scan
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: Q122cIpez64zhpBgPi0GMdgwVoplo8onT59jJD+zCpgzi1az3Fx1748i1BLSDZCi/rZDVyK0Y14WwAU0uELx/VSYDWrGxJnpyD5EH7tg2NHRtbIOAXk1gIxwEk8jZr2tFvJIEFS2rljlI+ZMrMc3ikp86hnVA8KVoDrfpQaiEB9igI9C4+gUA2Q4UaepR1rNReYOq+H/OLhHxNOSigrQylsPLJjzUTpKewMdAydLa1L6UiST85eU67lY83RmEQaPCY6XrJ5OTHGFG4dxIiR/ahUk1AbW5uBo2cIy3NNdTMcd1J9sXgU/xSUsRB3QwUbV/+uKVxVXPGW/kdDje04CC35HynuVVYnDiG3F0THTjDjv2Q6wPxDOs5nVwB/ivF/NAQ68MRVPuPeizbl/5Hh66kPPxL2DqL+s8KEluNDzq1SgZeYwkX+9629Ap/rrmPZ4ddunnaWeOVCaOD/hQbOPUVCBwKng+x7eWjX5MluQf4kjmRDR9Jg/qnXuxFiVF2ad7PPUA5kVIsnj6OkUXK32zITkpkT8b5+BDjrub2nzFm1qwyXwm+ru5c7wuQzK4gMOV0CcXFr5CdwaXQxPeMR5M3p0F2dHMP1b2lZqvyYxARptoUOcDb+vZ4r5HW4oSPDChhLOxxhgkmITtqGVaPoDxJ7ulqiT0ukWNBRdfiuXVTA=
  app: counterparty-service
  on:
    repo: spolnik/trading-office-counterparty-service
